import { siteConfig } from "@/config/site";

/** Raster widths emitted by `npm run images:build` (scripts/optimize-images.mjs). */
const RASTER_WIDTHS = [64, 128, 256, 384] as const;

/**
 * Tone sets the image pipeline knows about; keep in sync with the TONES table in
 * `scripts/optimize-images.mjs`. Only `brand` is generated by a plain
 * `npm run images:build` — the others must be requested explicitly, e.g.
 * `npm run images:build -- --tones=brand,gold`, otherwise the browser would 404.
 * For a one-off recolour without extra files, pass Tailwind filter utilities
 * through `className` instead (`grayscale invert`, `hue-rotate-[205deg]`, ...).
 */
export type BrandTone = "brand" | "gold" | "blue" | "violet" | "emerald" | "crimson" | "white" | "graphite";

const TONE_BASE: Record<BrandTone, string> = {
  brand: "radi-coin",
  gold: "radi-coin-gold",
  blue: "radi-coin-blue",
  violet: "radi-coin-violet",
  emerald: "radi-coin-emerald",
  crimson: "radi-coin-crimson",
  white: "radi-coin-white",
  graphite: "radi-coin-graphite"
};

interface BrandMarkProps {
  /** Display width in CSS pixels: drives the intrinsic size and the `sizes` hint. */
  size?: number;
  /** Colour set to load; generated asset sets only (see BrandTone). */
  tone?: BrandTone;
  className?: string;
  /** Eager + high priority loading; use for the one mark above the fold. */
  priority?: boolean;
  /** Decorative use (next to a text wordmark): hidden from assistive tech. */
  decorative?: boolean;
}

/**
 * The RADI emblem: `public/brand/radi-coin[-<tone>]-<width>.{webp,png}`.
 *
 * Those assets are generated from `assets/radi-coin-source.jfif` by
 * `npm run images:build` — already cropped, transparent, recoloured, sized and
 * metadata-free. A plain `<picture>` is therefore used on purpose: Next's
 * on-demand optimizer would only add `/_next/image` round-trips for bytes that are
 * already optimal. WebP is the primary source, palette PNG the fallback, and both
 * carry `srcSet` + `sizes` + intrinsic `width`/`height`, so there is no layout shift.
 */
export default function BrandMark({
  size = 128,
  tone = "brand",
  className,
  priority = false,
  decorative = false
}: BrandMarkProps) {
  const base = `/brand/${TONE_BASE[tone]}`;
  const srcSetFor = (extension: string) =>
    RASTER_WIDTHS.map((width) => `${base}-${width}.${extension} ${width}w`).join(", ");

  return (
    <picture>
      <source type="image/webp" srcSet={srcSetFor("webp")} sizes={`${size}px`} />
      <img
        src={`${base}-128.png`}
        srcSet={srcSetFor("png")}
        sizes={`${size}px`}
        width={size}
        height={size}
        alt={decorative ? "" : `${siteConfig.brand} — ${siteConfig.brandExpansion}`}
        aria-hidden={decorative || undefined}
        loading={priority ? "eager" : "lazy"}
        fetchPriority={priority ? "high" : "auto"}
        decoding="async"
        className={className}
      />
    </picture>
  );
}


