import { useState } from "react";

import BrandMark from "@/components/BrandMark";
import NeuralBackground from "@/components/NeuralBackground";
import { useLocale } from "@/context/LocaleContext";

export default function Hero() {
  const { content } = useLocale();
  const { hero } = content;
  /** Hovering the headline brightens the neural mesh slightly. */
  const [boost, setBoost] = useState(false);

  return (
    <section
      id="hero"
      className="snap-stop relative isolate flex min-h-[70vh] w-full flex-col items-center justify-center overflow-hidden bg-gradient-to-b from-black to-gray-900 px-6 py-20 text-center"
    >
      <NeuralBackground
        boost={boost}
        className="-z-10 [mask-image:radial-gradient(ellipse_at_50%_38%,black_28%,transparent_76%)]"
      />

      {/* Brand emblem, generated by `npm run images:build` (see BrandMark.tsx). */}
      <BrandMark
        size={176}
        priority
        className="mb-8 h-28 w-28 drop-shadow-[0_0_45px_rgba(34,211,238,0.35)] sm:h-36 sm:w-36 md:h-44 md:w-44"
      />

      <h1
        className="flex flex-col items-center"
        onPointerEnter={() => setBoost(true)}
        onPointerLeave={() => setBoost(false)}
      >
        {/* The three headline lines are brand identity: identical (English) in every
            language and always rendered LTR, so they never mirror in RTL locales. */}
        <span
          dir="ltr"
          className="bg-gradient-to-r from-blue-400 via-blue-500 to-cyan-400 bg-clip-text text-7xl leading-none font-black tracking-tight text-transparent md:text-9xl"
        >
          {hero.brand}
        </span>

        <span dir="ltr" className="mt-5 text-xl font-semibold text-white md:text-3xl">
          {hero.tagline}
        </span>

        <span
          dir="ltr"
          className="mt-4 max-w-3xl text-xs font-semibold tracking-[0.2em] text-blue-300 uppercase sm:text-sm md:text-base md:tracking-[0.35em]"
        >
          {hero.pageName}
        </span>
      </h1>

      <p className="mt-10 mb-10 max-w-2xl text-lg leading-relaxed text-gray-300 md:text-xl">{hero.subtitle}</p>

      <div className="flex flex-wrap justify-center gap-4">
        <a
          href="#roadmap"
          className="rounded-lg bg-blue-600 px-6 py-3 text-lg text-white transition hover:bg-blue-700"
        >
          {hero.ctaRoadmap}
        </a>

        <a
          href="#architecture"
          className="rounded-lg bg-gray-700 px-6 py-3 text-lg text-white transition hover:bg-gray-800"
        >
          {hero.ctaArchitecture}
        </a>
      </div>
    </section>
  );
}
